export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const GETWATCHLIST = 'GETWATCHLIST';
export const WATHCLISTERROR = 'WATCHLISTERROR';
export const POSTCREATED = 'POSTCREATED';
export const GETMYPOST = 'GETMYPOST';
export const COMMENTCREATED = 'COMMENTCREATED';
export const GETMYCOMMENT = 'GETMYCOMMENT';




